### ISSUE TITLE
Unable to untokenize

### ISSUE THREAD

**Issue by 409H** [ENS-Nifty/ens-nifty-frontend#51]
Since https://github.com/ENS-Nifty/ens-nifty-frontend/issues/46 is now fixed, I need to untokenize the errored NFT and re-tokenize the domain as ownership has changed for `parkingticket.eth`.

I'm unable to untokenize the errored NFT - see screen recording: https://i.gyazo.com/5470303b1ea595c9893655119bd9f977.mp4

There are no console errors when clicking "Untokenize".

**Comment by sudoryan** [comment]
Thanks so much @409H, 

This is a similar problem earlier on issue #46  except on the front end.
Great catch! 

PR #52 should resolve this.

**Comment by 409H** [comment]
Awesome - thanks so much!

**Comment by okwme** [comment]
Hi @409H,
Can you give it another try not that we've merged the PR into production?

**Comment by 409H** [comment]
@okwme hey, sorry for the late reply. This is working great for me now - thank you for the swift patches! 🍾

**Comment by okwme** [comment]
glad to hear it @409H : )
